# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: frontend

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: /home/server/

    steps:
    - uses: actions/checkout@v2
    - name: Pull from Github
      run: git clone https://github.com/simonsoeborg/02363-frontend.git

    - uses: actions/checkout@v2
    - name: Take down allready running docker container
      run:  docker-compose -f docker-compose-dev.yml down

    - uses: actions/checkout@v2
    - name: Docker compose with Dockerfile.dev
      run:  docker-compose -f docker-compose-dev.yml up -d --build