# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: frontend

on:
  push:
    branches: [ Development ]
  pull_request:
    branches: [ Development ]

jobs:
  build:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: /home/server/02363-frontend/

    steps:
    - uses: actions/checkout@v2
    - name: Pull from Github
      run: sudo git pull

    - uses: actions/checkout@v2
    - name: Docker compose with Dockerfile.dev
      run:  sudo docker-compose -f docker-compose-dev.yml up -d --build